name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.14.0
      with:
        go-version: 1.23
    - run: "go mod tidy"
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "latest"
        install-go: false
        working-directory:  ./app